project:
  type: book
  output-dir: _site

book:
  title: "Data for Decision Makers: Data Concepts and Applications"
  subtitle: Course Handbook
  author:
    - name: Proochista Ariana
      orcid: 0000-0002-0154-2237
      email: proochista.ariana@ndm.ox.ac.uk
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford      
    - name: Ernest Guevarra
      orcid: 0000-0002-4887-4415
      email: ernest@d4dm.org
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-all-about-data.qmd
    - 03-data-security.qmd
    - 04-data-tools.qmd
    - 05-data-entry-system.qmd
    - 06-intro-data-analysis.qmd
    - 07-exploratory-data-analysis.qmd
    - references.qmd
  # appendices: 
  #   - 12-mobile-device-setup.qmd
  #   - 13-odk-setup.qmd
  cover-image: images/d4dm_neg.png
  search: true
  repo-url: https://github.com/data4decisonmakers/data-concepts-applications/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  google-analytics: 
    tracking-id: ""
    anonymize-ip: true

crossref:
  appendix-title: Appendix
  appendix-delim: ":"

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: zephyr
    highlight-style: breeze
  pdf:
    documentclass: scrreprt
    papersize: a4
    toc: true
    toc-depth: 3
    highlight-style: breeze
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=2, columnseprule=true]
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/d4dm_neg.png
    toc: true
    toc-depth: 3
    highlight-style: breeze