project:
  type: book
  output-dir: _site

book:
  title: "Data for Decision Makers: Data Concepts and Applications"
  subtitle: Course Handbook
  author:
    - name: Proochista Ariana
      orcid: 0000-0002-0154-2237
      email: proochista.ariana@ndm.ox.ac.uk
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford      
    - name: Ernest Guevarra
      orcid: 0000-0002-4887-4415
      email: ernest@d4dm.org
      affiliation: 
        - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
          city: Oxford
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - part: Data Concepts
      chapters:
        - 01-introduction.qmd
        - 02-all-about-data.qmd
    - part: Data Case Studies
      chapters:
        - 03-case-study-one.qmd
        - 04-case-study-two.qmd
        - 05-case-study-three.qmd
        - 06-case-study-four.qmd
        - 07-case-study-five.qmd
    - part: Data Management
      chapters:
        - 08-data-security.qmd
        - 09-data-tools.qmd
        - 10-all-about-spreadsheets.qmd
        - 11-project-based-workflow.qmd
        - 12-data-entry-storage.qmd
    - part: Exploratory Data Analysis
      chapters:        
        - 13-exploratory-data-analysis.qmd
        - 14-univariate-statistics.qmd
        - 15-bivariate-statistics.qmd
        - 16-epi-statistics.qmd
    - references.qmd
  # appendices: 
  #   - 12-mobile-device-setup.qmd
  #   - 13-odk-setup.qmd
  cover-image: images/d4dm_neg.png
  search: true
  repo-url: https://github.com/data4decisonmakers/data-concepts-applications/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [linkedin, twitter, facebook]
  google-analytics: 
    tracking-id: G-FD0RT8JB4E
    anonymize-ip: true

crossref:
  appendix-title: Appendix
  appendix-delim: ":"

bibliography: references.bib
csl: apa-single-spaced.csl

format:
  html:
    theme: sandstone
    highlight-style: breeze-light
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 3
    highlight-style: breeze-light
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=2, columnseprule=true]
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/d4dm_neg.png
    toc: true
    toc-depth: 3
    highlight-style: breeze-light